services:
  weather_requester:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BROKER_ADDRESS=167.172.164.168
      - BROKER_PORT=1883
      - MQTT_USER=student
      - MQTT_PASSWORD=sys-wbud
      - STUDENT_ID=261356
      - LOCATIONS=10890
    restart: always

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data  # Wolumen współdzielący dane
    environment:
      - BROKER_ADDRESS=167.172.164.168
      - BROKER_PORT=1883
      - MQTT_USER=student
      - MQTT_PASSWORD=sys-wbud
      - DATA_FOLDER=/app/data
    command: ["python", "mqtt_subscriber.py"]  # Poprawiona nazwa pliku
    restart: always
