version: "3.8"
services:
  weather_requester:
    build:
      context: .
    environment:
      - LOCATION=${LOCATION}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_TOPIC=${MQTT_TOPIC}
    volumes:
      - .:/app
    ports:
      - "1883:1883" # MQTT broker port
